from groq import Groq
import os
from dotenv import load_dotenv
import re
import json

load_dotenv()

def gerar_sql(pergunta):
    estrutura_banco = '''
    CREATE TABLE "produtos" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nomeProduto" VARCHAR(255) NOT NULL,
    "codigoBarras" VARCHAR(13) NOT NULL,
    "categoriasId" INT NOT NULL
    );

    CREATE TABLE "categorias" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nomeCategoria" VARCHAR(255) NOT NULL
    );

    CREATE TABLE "vendas" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "dataHora" TIMESTAMP DEFAULT (NOW()),
    "quantidade" INT NOT NULL,
    "produtosId" INT NOT NULL
    );

    ALTER TABLE "produtos" ADD FOREIGN KEY ("categoriasId") REFERENCES "categorias" ("id") DEFERRABLE INITIALLY IMMEDIATE;

    ALTER TABLE "vendas" ADD FOREIGN KEY ("produtosId") REFERENCES "produtos" ("id") DEFERRABLE INITIALLY IMMEDIATE;
    '''

    prompt = f'''
    Atue como um especialista em SQL PostgreSQL
    Com base na modelagem abaixo, gere APENAS uma consulta SQL SELECT.
    Não explique nada.
    Não use markdown.
    Não use ```sql.
    Não gere INSERT, UPDATE, DELETE, DROP, ALTER, TRUNCATE, GRANT ou REVOKE.
    Não esquecer dos detalher específicos da linguagem POSTGRESQL, como aspas duplas para nomes de tabelas e colunas.

    MODELAGEM DO BANCO:
    {estrutura_banco}

    PERGUNTA DO USUÀRIO:
    {pergunta}
    '''
    
    client = Groq(api_key=os.getenv('GROQ_API_KEY'))
    resposta = client.chat.completions.create(
        model='llama-3.3-70b-versatile',
        messages=[
            {
                "role": "system",
                "content": "Você gera apenas SQL seguro para consulta em banco PostgreSQL"
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0
    )
    
    sql = resposta.choices[0].message.content.strip()
    sql = limpar_sql(sql)
    
    return sql
    
def limpar_sql(sql):
    sql = sql.replace('```sql', '').replace('```', '').strip()
    return sql

def validar_sql(sql):
    sql_limpo = sql.strip().upper()
    
    comandos_bloqueados = ['INSERT', 'UPDATE', 'DELETE', 'DROP', 'ALTER', 'TRUNCATE', 'REPLACE', 'CREATE', 'GRANT', 'REVOKE']
    
    if not sql_limpo.startswith('SELECT'):
        return False, "A consulta precisa começar com select."
    
    for comando in comandos_bloqueados:
        if re.search(rf"\b{comando}\b", sql_limpo):
            return False, f'Comando bloqueado encontrado: {comando.upper()}'

    return True, 'SQL válido'

def gerar_grafico(df, config):
    prompt = f'''
    Você é especialista em gráficos usando Plotly.

    DataFrame:

    {df.head(10)}

    Tipos:

    {df.dtypes}


    Configurações do usuário:

    {config}


    Retorne somente JSON:

    {{
    "tipo": "",
    "cor": "",
    "titulo": "",
    "mostrar_valores": false,
    "legenda": true
    }}

    O campo cor será usado diretamente no Plotly.

    Nunca retorne nomes de cores em português.

    Sempre retorne hexadecimal.

    Exemplos:

    verde -> #00FF00
    rosa -> #FF69B4
    azul -> #0000FF
    vermelho -> #FF0000

    Campo cor deve sempre seguir:
    "#RRGGBB"
    '''
    
    client = Groq(api_key=os.getenv('GROQ_API_KEY'))
    resposta = client.chat.completions.create(
        model='llama-3.3-70b-versatile',
        messages=[
            {
                "role": "system",
                "content": "Você escolhe o melhor tipo de gráfico e retorna apenas: bar, line ou area"
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0
    )
    
    grafico = resposta.choices[0].message.content.strip()

    grafico = grafico.replace("```json", "")
    grafico = grafico.replace("```", "")
    grafico = grafico.strip()

    return json.loads(grafico)